[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
program-b = "76XHb6msPokzjY4EZYMuXvJa3Arjr6BGi1qDUr1g9kYL"
program_a = "88NkftFqLEDTVHQm3Z6xW6THd8wiNBoLzM7LeVB5iq94"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
